### ISSUE TITLE
[FEAT] 이슈 및 PR 템플릿 등록

### ISSUE THREAD

**Issue by minjijeong98** [boostcampaitech7/level2-mrc-nlp-06#2]
## Background
- 프로젝트 기록의 가독성을 높이기 위해 이슈 및 PR에서 일관된 형식을 사용할 수 있도록 템플릿을 등록합니다.
- 템플릿 파일은 `.github` 폴더에 저장됩니다.

## Todo
- [x] Issue - feature request 템플릿 생성
- [x] Issue - bug report 템플릿 생성
- [x] Pull Request 템플릿 생성
