### ISSUE TITLE
[FEAT] EDA 파일 업로드 요청

### ISSUE THREAD

**Issue by unsolomon** [boostcampaitech7/level2-mrc-nlp-06#7]
## Background
-
feature/EDA의 Branches에 EDA_team_folder가 생성되었습니다.
각자 작업한 EDA 파일을 이 폴더에 업로드해 주시면 감사하겠습니다

업로드 위치: feature/EDA Branches의 level2-mrc-nlp-06/EDA_team_folder/

업로드 방법:
1. 'level2-mrc-nlp-06' 저장소를 로컬에 clone 합니다. (이미 clone 한 경우 pull로 최신 상태로 업데이트)
2. feature/EDA 브랜치로 checkout 합니다: git checkout feature/EDA
3. checkout 후 최신 상태를 유지하기 위해 pull 명령어를 실행합니다: git pull origin feature/EDA
4. 'EDA_team_folder' 폴더에 자신의 EDA 파일을 추가합니다.
5. 변경사항을 커밋합니다: git commit -m "Add EDA file for [본인 이름/주제]"
6. 변경사항을 push 합니다: git push origin feature/EDA

주의사항:
- 파일명은 '[본인이름]_EDA.ipynb' 형식으로 작성해 주세요.
- 다른 팀원의 파일을 수정하지 않도록 주의해 주세요.
- 24/10/13  18:00 까지 제출 부탁드리겠습니다

모든 팀원들의 파일이 업로드되면, 이를 바탕으로 통합 작업을 진행하겠습니다.
질문이나 문제가 있으면 이 이슈에 댓글로 남겨주세요.

## Todo
- [ ] EDA 파일 작성
- [ ] EDA_team_folder에 파일 업로드
- [ ] 변경사항 커밋 및 푸시
- [ ] 추후 통합

## 체크포인트
- [x] 서태영: EDA 파일 업로드 완료
- [x] 이상의: EDA 파일 업로드 완료
- [x] 이정휘: EDA 파일 업로드 완료
- [x] 정민지: EDA 파일 업로드 완료

## See also
- #3
